[[handlers]]
type = "RoleWizard"
allowed_role_grants = [ "political animal" ]
allowed_role_revoke = [ "political animal" ]

[[handlers]]
type = "AckMessage"
deny_channels = [ "never_ack_here" ]

[[handlers]]
type = "VerbalMorality"
bad_words = [ 
  "trump", "clinton", "republican", "democrat", "boris johnson", "bojo",
  "orange tornado", "orange man", "biden", "sleepy joe", "sleepy eyes joe",
  "nazi"
]
allow_users_by_tag = [ "Command-R#3084" ] # people on the irc bridge cannot join
                                          # #politics, so don't nudge them to
deny_channels = [ "politics" ]
warning_message = """\
Hey, that sounds like it may be best taken to the #politics channel. If you \
don't see that channel, you can request it by @ messaging me with 'role grant \
political animal'. If you change your mind I can revoke that role as well.\
"""
counter_db_name = "politics_nudger"

[[handlers]]
type = "VerbalMorality"
bad_words = [
  # variations on "damn"
  "damn", "damnit", "dammit",
  # variations on "shit"
  "shit", "shitty",
  # varations on "fuck"
  "fuck", "fucking", "fucker",
  # other words of ill-repute
  "bastard", "cock", "hell", "dick", "bitch", "ass hole", "asshole"
]
allow_users_by_tag = []
deny_channels = []
warning_message = """\
{{user}} you are fined one credit for a violation of the Verbal Morality \
Statute.\
"""
counter_db_name = "demolition_man"
